### ISSUE TITLE
0.2.0.0 failing on stackage

### ISSUE THREAD

**Issue by cdornan** [tel/saltine#58]
We are seeing:

> Configuring saltine-0.2.0.0...
Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.4: The pkg-config package 'libsodium'
version ==1.0.18 || >1.0.18 is required but the version installed on the
system is version 1.0.16

For now we have reverted to 0.1.1.1

**Comment by linearray** [comment]
Is this still an ongoing problem or can libsodium be upgraded in stackage?

**Comment by charles37** [comment]
> Is this still an ongoing problem or can libsodium be upgraded in stackage?

> saltine                       > Configuring saltine-0.2.0.1...
> saltine                       > Cabal-simple_SvXsv1f__3.6.3.0_ghc-9.2.5: The pkg-config package 'libsodium'
> saltine                       > version >=1.0.18 is required but the version installed on the system is
> saltine                       > version 1.0.16
> saltine                       > 

This is still an ongoing problem

**Comment by linearray** [comment]
AFAICT the pin to 0.1.1.1 in stackage is causing problems, because 0.1.1.1 does not work with newer `bytestring`, so saltine gets dropped entirely.

@cdornan can you try reverting https://github.com/commercialhaskell/stackage/commit/e396a6ae1fb2ad00cc82dbaf03f9dba3ba8f08f1 because it appears to me stackage installs libsodium 1.0.18 nowadays and everything should just work

**Comment by cdornan** [comment]
You have just caught me as I am just about to sign off on the rota (we do one week in 8) &mdash; in future the safest thing to do is raise a PR and let whoever is 'on' merge it.

I am removing the pin and closing the issue.
